### ISSUE TITLE
Sleeping in bag messes up rewpawn

### ISSUE THREAD

**Issue by Moxiesan** [henkelmax/sleeping-bags#10]
### Bug description

![Capture](https://github.com/user-attachments/assets/dd1dbb9c-98af-42b1-8667-799b14f4303f)
Once we set a respawn point in bed, then use a sleeping bag, the resulting error occurs. "You have no home bed or charged respawn anchor, or it was obstructed." I have tried putting a bed into the middle of the room to ensure it is not obstructed, but still getting the error. No errors in the logs.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.9

### Mod loader and version

Forge - 47.3.0

### Steps to reproduce

1. Place bed and set spawn.
2. Sleep in sleeping bag.
3. Die.
4. Walk back from spawn.

### Expected behavior

1. Place bed and set spawn.
2. Sleep in sleeping bag.
3. Die.
4. Respawn at bed.

### Log files

N/A

**Comment by henkelmax** [comment]
I just tested it and it works perfectly fine. Please check if other mods cause that.
